name: ajanda
description: Ajanda, geri sayım ve bildirim.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_calendar_carousel: ^1.4.12
  intl: 0.16.1
  path_provider: ^1.6.10
  sqflite: any
  flutter_local_notifications: ^1.4.4+1
  platform: ^2.2.1
  firebase_admob: ^0.9.3+4
  workmanager: ^0.2.3
  dynamic_theme: ^1.0.1
  flutter_mailer: ^0.5.1
  image_picker: ^0.6.7+6
  file_picker: ^1.13.3
  permission_handler: ^5.0.1+1
  device_info: ^0.4.2+7







  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/turkey-flag-icon-128.png
    - assets/images/united-kingdom-flag-icon-128.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DoppioOne
      fonts:
        - asset: assets/fonts/DoppioOne-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Italic-VariableFont_wght.ttf
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-VariableFont_wght.ttf
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata-VariableFont_wdth,wght.ttf
    - family: LibreBaskerville
      fonts:
        - asset: assets/fonts/LibreBaskerville-Regular.ttf
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Italic-VariableFont_wght.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-LightItalic.ttf
    - family: Pangolin
      fonts:
        - asset: assets/fonts/Pangolin-Regular.ttf
    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-VariableFont_wght.ttf
    - family: RussoOne
      fonts:
        - asset: assets/fonts/RussoOne-Regular.ttf
    - family: Titillium
      fonts:
        - asset: assets/fonts/TitilliumWeb-Regular.ttf


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
